# Change these first
owner: BlakeRain # Your GitHub username
repo: upptime.blakerain.com # Your Github repository name

# Add your sites here
sites:
  - name: blakerain.com
    url: https://blakerain.com
  - name: blakerain.com (search)
    url: https://blakerain.com:9443/

status-website:
  cname: status.blakerain.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
